### PR TITLE
Kh issue 13

### PR DESCRIPTION
**Pull request by Jarmahent**
### Acknowledgments

- [x] I confirm that I wrote the code based on the [company guidelines](https://github.com/0x4447/0x4447-The-Library/tree/master/Blueprints/programmer#coding-style).
- [x] I confirm that I followed the Git flow described in the [company guidelines](https://github.com/0x4447/0x4447-The-Library/tree/master/Blueprints/programmer#how-to-work-with-github).

### Description

Adding `05_diet.js` file to remove html comments, css comments, and JS comments from input html files.

### Example

```js
const htmlFile = `
<html>
<script>
  console.log("Hello world!") // This will be removed
</script> // This will be removed

<!-- Html comment will be removed -->

<!-- Html comment -->
/*

Block Comment will
also be removed

*/
</html>
`;

let noComments = htmlFile.replace(
  /(\<!--[\s\S]*?-->)|^\s*$|(\/\*[\s\S]*?\*\/)|[^\S:]\/\/.*$/gm,
  ''
);

console.log(noComments)
```
Output:
```html
<html>
<script>
  console.log("Hello world!")
</script>





</html>
```

Issue(s): #13

### CODE REVIEW

**Comment by Jarmahent** [comment]
That makes sense what should the file be named?

**Comment by davidgatti** [comment]
File named? the promises should be in the `05_diet.js` file. and if you ask for the function names? Not sure, didn't think about it. Think about the task, what it is doing, and based on that come up with something - we can always fine tuned it.

**Comment by Jarmahent** [comment]
Ok changes have been made here is examples for the files that were processes with these changes:

### HTML File before and after
### Before
```html
<script>

//
//	Loop over all the nav URL so we can update the active link.
//
$.each($(".navbar-link"), function() {

	//
	//	1. Get HREF attribute of the menu item that was clicked.
	//
	let href = $(this).attr('href');

	//
	//	2. Check if we are dealing with the home menu item. since this is
	//		an edge case that we have to consider.
	//
	if(href !== '/')
	{
		href = '/' + href
	}

	//
	//	3. Get the current path of the window.
	//
	let current_path = window.location.pathname

	//
	//	4. Check if the HREF matches the current path.
	//
	if(href === current_path)
	{
		//
		//	Add the `active-link` to lighten font weight this way we can
		//	visual show the active page.
		//
		$(this).addClass('active-link');
	}

});

</script>
```
### After
```html
<script>

$.each($(".navbar-link"), function() {




	let href = $(this).attr('href');





	if(href !== '/')
	{
		href = '/' + href
	}




	let current_path = window.location.pathname




	if(href === current_path)
	{
	
	
	
	
		$(this).addClass('active-link');
	}

});

</script>
```
------------
### CSS File before and after
### Before

```css
/* GLOBAL STYLES
-------------------------------------------------- */
/* Padding below the footer and lighter body text */

/* roboto-mono-100 - latin */
@font-face {
    font-family: "Roboto Mono";
    font-style: normal;
    font-weight: 100;
    src: url("../font/roboto-mono-v5-latin-100.eot"); /* IE9 Compat Modes */
    src: local("Roboto Mono Thin"), local("RobotoMono-Thin"),
        url("../font/roboto-mono-v5-latin-100.eot?#iefix")
            format("embedded-opentype"),
        /* IE6-IE8 */ url("../font/roboto-mono-v5-latin-100.woff2")
            format("woff2"),
        /* Super Modern Browsers */ url("../font/roboto-mono-v5-latin-100.woff")
            format("woff"),
        /* Modern Browsers */ url("../font/roboto-mono-v5-latin-100.ttf")
            format("truetype"),
        /* Safari, Android, iOS */
            url("../font/roboto-mono-v5-latin-100.svg#RobotoMono") format("svg"); /* Legacy iOS */
}
```

### After
```css




@font-face {
    font-family: "Roboto Mono";
    font-style: normal;
    font-weight: 100;
    src: url("../font/roboto-mono-v5-latin-100.eot"); 
    src: local("Roboto Mono Thin"), local("RobotoMono-Thin"),
        url("../font/roboto-mono-v5-latin-100.eot?#iefix")
            format("embedded-opentype"),
         url("../font/roboto-mono-v5-latin-100.woff2")
            format("woff2"),
         url("../font/roboto-mono-v5-latin-100.woff")
            format("woff"),
         url("../font/roboto-mono-v5-latin-100.ttf")
            format("truetype"),
        
            url("../font/roboto-mono-v5-latin-100.svg#RobotoMono") format("svg"); 
}
```
-----------

### JS File before and after
### Before
```js
let cache_name = 'v1';

//
//	Listen to the Install event and when this happens add the files to the
//	cash.
//
self.addEventListener('install', function(event) {

	//
	//	1.	All the assets that needs cashing
	//
	let assets = [
		'./',
		'./index.html',
		'./service_worker.js',
		'./assets/js/jquery-3.2.1.min.js',
		'./assets/js/popper-1.13.0.min.js',
		'./assets/js/bootstrap-v4.0.0-beta.2.min.js',
		'./assets/css/bootstrap-3.3.7.min.css',
		'./assets/css/style.css',
		'./assets/logo.png'
	];

	//
	//	2.	Set the promise chain in a clear variable which will help
	//		us more easily reason about the code
	//
	let add_assets = caches.open(cache_name)
		.then(function(cache) {

			return cache.addAll(assets);

		}).catch(function(error) {

			console.log(error)

		});

	//
	//	3.	Tell the event to wait until we finish
	//
	event.waitUntil(add_assets);

});
```
### After
```js
let cache_name = 'v1';





self.addEventListener('install', function(event) {

	
	
	
	let assets = [
		'./',
		'./index.html',
		'./service_worker.js',
		'./assets/js/jquery-3.2.1.min.js',
		'./assets/js/popper-1.13.0.min.js',
		'./assets/js/bootstrap-v4.0.0-beta.2.min.js',
		'./assets/css/bootstrap-3.3.7.min.css',
		'./assets/css/style.css',
		'./assets/logo.png'
	];

	
	
	
	
	let add_assets = caches.open(cache_name)
		.then(function(cache) {

			return cache.addAll(assets);

		}).catch(function(error) {

			console.log(error)

		});

	
	
	
	event.waitUntil(add_assets);

});
```

**Comment by davidgatti** [comment]
OK, looks cool. I was hoping to test this today, but I can't I'll do it tomorrow, my morning.

**Comment by davidgatti** [comment]
OK, so after going over your changes this are my findings:

# Nr. 1
we need to skip the asset folder and only do the `view` one since turns out that the `bootstrap-v4.0.0.min.css` is all commented - no idea how that works, but the effect is that we remove the whole CSS style from the file, and it stops working

# Nr. 2

Test how your changes are performing on the company website. GO over this [local setup](https://github.com/0x4447/0x4447-the-library/tree/development/Blueprints/programmer/front-end/local-setup), this way you can see what happens to a page once you run your code. To me it showed immediately what was wrong with the CSS, and there is something wrong also with jQuery where it stops working, but it think this will solve it self, once we focus only on the `view` folder.

# Nr. 3

Lets talk how your wrote the code ;) it is not bueno:

1. I did tell you to make the code look the same as the other file, when it comes to the structure, and if you open any other file that I wrote you'll see that what I did and you did differs a lot. It is a completely different way of structuring the file.
2. Your first task that I give you was to work on the ESLint to make you familiar with the coding style described [here](https://github.com/0x4447/0x4447-the-library/tree/development/Blueprints/programmer#coding-style), and if I look at the code I see the ESLint would throw quite the amount of errors.
3. I the `03_data.js` file I already read the folder structure, and save all the pats in the container object, you should reuse that - no need to re-read again the folder structure.

So:

1. Setup the local environment with the company site so you can see the effects
1. Make the file look like the rest when it comes to the code structure.
1. Make the code look nicer y running ESLint and comparing it to what I did in the past.
1. reuse the folder paths that are already read
1. Only parse the `views` folder.

**Comment by Jarmahent** [comment]
Got it will do 👍🏻

**Comment by Jarmahent** [comment]
That sucks I tried to make the code structure as similar to what you do but I guess it wasn't correct.

**Comment by davidgatti** [comment]
@Jarmahent now that we have code structured the same way as the rest of the project, you remember that I mentioned to split the reg exp in 3 parts, HTML, CSS and JS? Could you spit the CSS and JS reg ex?

**Comment by Jarmahent** [comment]
If I split the js and css comments one of them will be useless because they're both the same regex so if the `remove js` function runs first it will remove js and css comments and then the `remove css` function will run and it will do nothing since JS and css have the exact same comment syntax;


```
// Css comment 
// JS comment

/* Css
Multi line 
Comment 
*/

/* Js
Multi line 
Comment 
*/
```

**Pull request merged**
